#version: '3.9'

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
   
    environment:
      POSTGRES_PASSWORD: 4444 
      POSTGRES_DB: pomodoro
    ports: 
      - '5432:5432'

  cache:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - '6379:6379'